### ISSUE TITLE
下拉刷新界面会卡住

### ISSUE THREAD

**Issue by AllenChow** [MarkMjw/PullToRefresh#3]
![qq20140217223143](https://f.cloud.github.com/assets/3684781/2186145/40c20742-97e1-11e3-891c-a3eca24986b8.png)
就是下拉刷新的时候，力度要小，不要触发下拉刷新的基础下拉几次就会出现以上情况.，安卓版本4.0以上都会出现。4.0以下没有测过。

**Comment by hanxuhui** [comment]
我也遇到了这样的问题，看了半天也不知道怎么弄，希望作者解决一下。谢谢。
